# 明道安装管理器下载
# mingdao_download_url: "https://pdpublic.mingdao.com/private-deployment/1.8.1/mingdaoyun_private_deployment_captain_linux.tar.gz"
# 2021-1-07 更新2.1.1
# mingdao_download_url: "https://pdpublic.mingdao.com/private-deployment/2.1.1/mingdaoyun_private_deployment_captain_linux.tar.gz"
# 2021-4-12 更新2.4.1
mingdao_download_url: "https://pdpublic.mingdao.com/private-deployment/2.4.1/mingdaoyun_private_deployment_captain_linux.tar.gz"


